# Generated by Django 5.2.3 on 2025-06-26 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('referee_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for the referee', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the referee', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Date of birth of the referee')),
                ('exp', models.IntegerField(help_text='Number of years of experience of the referee')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for the team', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the team', max_length=100, unique=True)),
                ('main_stadium', models.CharField(help_text='Main stadium of the team', max_length=100, unique=True)),
                ('city', models.CharField(help_text='City of the stadium', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for the player', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the player', max_length=100, unique=True)),
                ('date_of_birth', models.DateField(help_text='Date of birth of the player')),
                ('start_year', models.IntegerField(help_text='Starting year of the player')),
                ('shirt_number', models.PositiveIntegerField(help_text='Shirt number of the player')),
                ('team', models.ForeignKey(help_text='Team of the player', on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for the match', primary_key=True, serialize=False)),
                ('match_date', models.DateField(help_text='Date of the match')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='api.referee')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_records', to='api.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
