# Generated by Django 5.2.3 on 2025-06-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(help_text='Team of the player', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team'),
        ),
    ]
